#.travis.yml

language: node_js
node_js:
  - "9.0"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:

notifications:
  email:
    on_failure: change
    on_success: change
